import { StyleSheet, Dimensions } from "react-native"

const { width, height } = Dimensions.get("window")

// Export the absoluteFillObject separately for TypeScript compatibility
export const absoluteFillObject = {
  position: "absolute",
  top: 0,
  left: 0,
  bottom: 0,
  right: 0,
}

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ff9500",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  searchContainer: {
    position: "absolute",
    top: height * 0.07,
    width: "100%",
    alignItems: "center",
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: width * 0.025,
    height: height * 0.05,
  },
  searchInput: {
    flex: 1,
    marginLeft: width * 0.02,
    color: "#000",
  },
  searchBlock: {
    backgroundColor: "white",
    borderRadius: width * 0.03,
    width: width * 0.9,
    alignSelf: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    marginBottom: height * 0.01,
  },
  filters: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    width: "100%",
    paddingHorizontal: width * 0.025,
  },
  filterButton: {
    backgroundColor: "white",
    borderRadius: width * 0.03,
    paddingHorizontal: width * 0.03,
    paddingVertical: height * 0.008,
    marginHorizontal: width * 0.01,
  },
  filterText: {
    fontSize: width * 0.032,
    color: "#000",
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    height: height * 0.075,
    width: "100%",
    backgroundColor: "#ff9500",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderTopWidth: 0.5,
    borderColor: "#eee",
    zIndex: 10,
  },
  predictionList: {
    maxHeight: height * 0.25,
    borderTopWidth: 1,
    borderColor: "#eee",
  },
  predictionItem: {
    padding: height * 0.013,
  },
  predictionText: {
    fontSize: width * 0.042,
    color: "#000",
  },
  floatingButtons: {
    position: "absolute",
    bottom: height * 0.1,
    right: width * 0.05,
    flexDirection: "column",
    alignItems: "flex-end",
    gap: height * 0.015,
  },
  floatButton: {
    backgroundColor: "#ff9500",
    padding: height * 0.012,
    borderRadius: 50,
    elevation: 3,
  },
  placeCard: {
    position: "absolute",
    height: height * 0.15,
    bottom: height * 0.115,
    left: width * 0.1,
    right: width * 0.1,
    backgroundColor: "white",
    borderRadius: width * 0.04,
    padding: width * 0.04,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    zIndex: 10,
  },
  placeName: {
    fontSize: width * 0.045,
    fontWeight: "bold",
    marginTop: height * -0.006,
    marginBottom: height * 0.004,
  },
  placeRating: {
    fontSize: width * 0.035,
    color: "#333",
    marginBottom: height * 0.001,
  },
  placeDistance: {
    fontSize: width * 0.035,
    color: "#333",
    marginBottom: height * 0.01,
  },
  carouselContainer: {
    position: "absolute",
    bottom: height * 0.08, 
    height: height * 0.35, 
    width: "100%",
    alignItems: "center",
  },
  carouselCard: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 12,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  cardImageSection: {
    flexDirection: "row",
    height: height * 0.15,
    marginBottom: 10,
    gap: 8,
  },
  cardMainImageContainer: {
    flex: 2,
    backgroundColor: "#f0f0f0",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  cardSideImagesContainer: {
    flex: 1,
    gap: 8,
  },
  cardSideImageContainer: {
    flex: 1,
    backgroundColor: "#f0f0f0",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  cardImagePlaceholder: {
    fontSize: width * 0.035,
    color: "#999",
    fontWeight: "500",
  },
  cardInfoSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  cardLeftInfo: {
    flex: 1,
  },
  cardRightInfo: {
    alignItems: "flex-end",
  },
  badges: {
    flexDirection: "row",
    marginTop: 8,
    gap: 8,
    flexWrap: "wrap",
  },
  badge: {
    backgroundColor: "#eee",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    fontSize: 12,
  },
  bottomSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    zIndex: 20,
  },
  bottomSheetHandle: {
    width: 40,
    height: 5,
    backgroundColor: "#ccc",
    borderRadius: 3,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 0,
  },
  bottomSheetContent: {
    padding: 15,
    paddingTop: 0,
    flex: 1,
  },
  bottomSheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  bottomSheetTitle: {
    fontSize: width * 0.06,
    fontWeight: "bold",
    flex: 1,
    marginBottom: 15,
  },
  favoriteButton: {
    padding: 8,
  },
  bottomSheetRating: {
    fontSize: width * 0.04,
    color: "#333",
    fontWeight: "600",
  },
  bottomSheetDistance: {
    fontSize: width * 0.04,
    color: "#333",
  },
  bottomSheetBadges: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
    marginBottom: 10,
  },
  bottomSheetDescription: {
    fontSize: width * 0.04,
    color: "#666",
    marginTop: 20,
    textAlign: "center",
  },
  bottomSheetSectionTitle: {
    fontSize: width * 0.05,
    fontWeight: "600",
    color: "#333",
    marginBottom: 10,
  },
  bottomSheetText: {
    fontSize: width * 0.04,
    color: "#666",
    lineHeight: width * 0.06,
    marginBottom: 15,
  },
  imageSection: {
    flexDirection: "row",
    height: height * 0.25,
    marginBottom: 15,
    gap: 10,
    marginTop: -5,
  },
  mainImageContainer: {
    flex: 2,
    backgroundColor: "#f0f0f0",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  imagePlaceholder: {
    fontSize: width * 0.04,
    color: "#999",
    fontWeight: "500",
  },
  sideImagesContainer: {
    flex: 1,
    gap: 10,
  },
  sideImageContainer: {
    flex: 1,
    backgroundColor: "#f0f0f0",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  sideImagePlaceholder: {
    fontSize: width * 0.035,
    color: "#999",
    fontWeight: "500",
  },
  placeInfoSection: {
    marginBottom: 15,
  },
  placeInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  placeInfoLeft: {
    flex: 1,
    paddingRight: 20,
  },
  placeInfoRight: {
    alignItems: "flex-end",
  },
  tabContainer: {
    flexDirection: "row",
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
  },
  activeTab: {
    borderBottomWidth: 2,
    borderBottomColor: "#007AFF",
  },
  tabText: {
    fontSize: width * 0.04,
    color: "#666",
    fontWeight: "500",
  },
  activeTabText: {
    color: "#007AFF",
    fontWeight: "600",
  },
  tabContent: {
    flex: 1,
    paddingTop: 5,
  },
  infoTabContent: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 20,
  },
  infoActionButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    paddingHorizontal: 40,
    marginTop: 10,
  },
  infoActionButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#f5f5f5",
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
})